[package]
name = "parallel-update-cli"
version = "0.1.0"
edition = "2021"
authors = ["Douile"]
license = "MIT"
rust-version = "1.74.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parallel-update = { path = "../lib" }
parallel-update-config = { path = "../config", features = ["serde", "clap"] }
toml = "0.8.8"
clap = { version = "4.4.11", features = ["cargo", "derive"] }